// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pxabqfsdprlmqgkwnpdc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB4YWJxZnNkcHJsbXFna3ducGRjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk0ODA4MTYsImV4cCI6MjA2NTA1NjgxNn0.P1v4doExqIRXArLIbIrJlUDZI7rnWUrNbzxjd5To2GM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});